name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU (for Linux aarch64)
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.2.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_BEFORE_BUILD: python -m pip install -U pip && rm -rf build
          CIBW_ARCHS_LINUX: auto aarch64

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: built-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./dist/*.whl

      - name: Build source distribution
        if: matrix.os == 'ubuntu-latest'
        run: python -m pip install build && python -m build --sdist --outdir dist

      - name: Upload sdist
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: built-sdist
          path: ./dist/*.tar.gz

  publish:
    needs: build
    runs-on: ubuntu-latest
    # pypi trusted publishing via OIDC
    permissions:
      id-token: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: built-*
          path: dist
          merge-multiple: true

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
